FROM tomcat:9.0

# Remove default webapp
RUN rm -rf /usr/local/tomcat/webapps/ROOT

# Copy WAR generated by Maven
COPY target/journey_project.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080

CMD ["catalina.sh", "run"]
